### ISSUE TITLE
Fetch All Google Fonts

### ISSUE THREAD

**Issue by hiro288** [EusebiuOprinoiu/polygon-customizer-boilerplate#1]
How can i fetch all the google fonts? I'm using this code:

```
$wp_customize->add_setting(
          'gfont',
          array(
              'default'           => 'Open Sans',
              'sanitize_callback' => 'sanitize_text_field',
          )
);
```

```
  $wp_customize->add_control(
      new Polygon_Customize_Google_Fonts_Control(
          $wp_customize,
          'gfont',
          array(
              'label'       => esc_html__( 'Google Font', 'polygon' ),
              'description' => esc_html__( 'This is a temporary description.', 'polygon' ),
              'section'     => 'footer_section',
              'fonts'       => array(  'Open Sans', 'Noto Sans', 'Droid Sans' ),
              // If 'fonts' is available, the next parameters will not be used.
              'api_key'     => 'myapikey',
              'amount'      => 'all',          // Number of fonts.
              'cache_time'  => 30,          // Number of days.
          )
      )
  );`
```

if i remove 'fonts' it throws an error

**Comment by EusebiuOprinoiu** [comment]
That's strange! What kind of error do you get?
The 'fonts' parameter is optional and everything should work properly if you used a valid API key.
If you haven't, here's how you can do it:
- Visit https://console.cloud.google.com
- Create a new project
- Go to APIs Overview
- Turn on Web Fonts Developer API
- Click Credentials under the API Manager
- Create a new key

This code below is all you need to display all fonts:

``` php
$wp_customize->add_control(
    new Polygon_Customize_Google_Fonts_Control(
        $wp_customize,
        'headings_font_font_family',
        array(
            'label'      => esc_html__( 'Headings Font', 'polygon' ),
            'section'    => 'typography_settings',
            'api_key'    => 'API-KEY',
            'amount'     => 'all',    // Number of fonts: number or 'all'.
            'cache_time' => 30,       // Number of days to cache.
        )
    )
);
```

**Comment by hiro288** [comment]
If i change 'amount' to a number it shows this error:

`Warning: array_slice() expects parameter 1 to be array, null given in C:\wamp\www\...\controls\google-fonts.php on line 198`

if i use 'all' it prints nothing.

btw I'm using a valid API key.

**Comment by hiro288** [comment]
with debug enabled i'm also getting this:

`Notice: Undefined property: stdClass::$items in C:\wamp\www\...\controls\google-fonts.php on line 195`

**Comment by EusebiuOprinoiu** [comment]
There is a problem with the response you get from Google.
Check to see if you get a valid list of fonts when accessing these links with your API Key or you get some sort of error.
https://www.googleapis.com/webfonts/v1/webfonts?key=API-KEY
https://www.googleapis.com/webfonts/v1/webfonts?sort=popularity&key=API-KEY

**Comment by EusebiuOprinoiu** [comment]
Also, make sure to delete the 'polygon_google_fonts' and 'polygon_popular_google_fonts' transients.
They cache the response from Google for the number of days you configured in the control.
My guess is that you loaded the customizer before you configured a valid API key and an invalid response was cached in those transients. And now, even if everything is correct, you get the old, invalid data stored inside them.

Add this snippet in your `functions.php`, load your website to delete the transients, remove the snippet and then load your customizer.

``` php
delete_transient( 'polygon_google_fonts' );
delete_transient( 'polygon_popular_google_fonts' );
```

**Comment by hiro288** [comment]
It works now, deleting the transient did the trick, thanks!

**Comment by EusebiuOprinoiu** [comment]
Awesome! I'm glad it was all sorted out!
